stages:
  - deploy

deploy:
  image: yilutech/docker-tz:19.03.8
  stage: deploy
  only:
    - tags
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "https://gitlab.yilu.co/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
